services:
  - type: web
    name: okx-tg-bot2
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py  # вместо gunicorn!
    envVars:
      - key: PORT
        value: 10000
